name: "Production Blue-Green Deployment"

# This workflow triggers on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # We assume your Terraform files are in a 'terraform'.
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- ADD THIS STEP BELOW ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0" # Or your preferred version
          terraform_wrapper: false


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      

      # 1. Get AWS Account ID (to find your S3 bucket dynamically)
      - name: Get AWS Account ID
        id: account
        run: echo "id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      - name: Debug File Location
        run: |
          echo "Current directory: $(pwd)"
          echo "Searching for files..."
          find . -maxdepth 3 -name "application.py"
          find . -maxdepth 3 -name "requirements.txt"  

      - name: Package Application Code
        working-directory: .
        run: |
         # Use -j to put application.py and requirements.txt at the ROOT of the zip
          zip -j ./app-${{ github.sha }}.zip ./src/application.py ./src/requirements.txt
          
          # Move the zip into the terraform folder so the following steps find it
          mv ./app-${{ github.sha }}.zip ./terraform/
          
          echo "Verifying zip content:"
          zip -sf ./terraform/app-${{ github.sha }}.zip
      # 3. Upload Zip to S3
      - name: Upload to S3
        run: |
          aws s3 cp ./app-${{ github.sha }}.zip s3://vijaya-eb-artifacts-${{ steps.account.outputs.id }}/app-${{ github.sha }}.zip
          echo "Waiting 15 seconds for S3 consistency..."
          sleep 30

      # 4. Terraform Apply (Deploy to Green)
      - name: Terraform Init
        run: terraform init
      - name: Terraform Import Existing Resources
        run: |
          terraform import aws_elastic_beanstalk_application.app vijaya-blue-green-app || true
          terraform import aws_s3_bucket.eb_artifacts vijaya-eb-artifacts-272183979798 || true
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="app_version=app-${{ github.sha }}"

      # 5. Health Check (plz Wait for Green to be Ready) 
      - name: Wait for Green Health
        run: |
          echo "Waiting for app-green to reach Ready state..."
          # Loop for 15 minutes (30 checks * 30 seconds)
          for i in {1..30}; do
            STATUS=$(aws elasticbeanstalk describe-environments --environment-names app-green --query "Environments[0].Status" --output text)
            HEALTH=$(aws elasticbeanstalk describe-environments --environment-names app-green --query "Environments[0].Health" --output text)
            
            echo "Current Status: $STATUS, Health: $HEALTH (Attempt $i)"
            
            if [ "$STATUS" == "Ready" ]; then
              echo "Environment is Ready!"
              exit 0
            fi
            
            sleep 30
          done
          echo "Error: Environment timed out or failed to reach Ready state."
          exit 1

      # 6. The Final Swap (Blue <-> Green)
      - name: Swap CNAMEs
        run: |
          aws elasticbeanstalk swap-environment-cnames \
            --source-environment-name app-blue \
            --destination-environment-name app-green